<a href="https://colab.research.google.com/github/Manish142/NLP/blob/Edits/Copy_of_Python_basics_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 

This file illustrates the key concepts involved in the learning of Numpy library.

## Basics of Numpy

Importing the numpy library:

In [18]:
import numpy as np

The shape, dimension and data type of the numpy array is obtained as follows:

In [19]:
a = np.arange(12).reshape(3,4)
a_shape = a.shape                  # Shape of the numpy array a 
a_dim = a.ndim                     # Dimension of the numpy array a 
a_data_type = a.dtype.name         # Data type of the variable a

print('The shape of the ndarry a is',a_shape)
print('The dimension of the ndarry a is', a_dim)
print('The data type of elements of the array a is', a_data_type)

The shape of the ndarry a is (3, 4)
The dimension of the ndarry a is 2
The data type of elements of the array a is int64


## Creating Numpy Array


Python Sequence to numpy array

In [20]:
a1D = np.array([1, 2, 3, 4])

In [21]:
a1D

array([1, 2, 3, 4])

We can also convert list into numpy array as follows:

In [22]:
list1 = [5,6,7,8,9]
a = np.array(list1)
type(a)

numpy.ndarray

Creating numpy using functions

In [23]:
# NumPy array creation functions
r = np.arange(10)
r_1 = np.linspace(2., 4., 6)

print('The numpy array r is as follows:', r)
print('The numpy array r_1 is as follows:', r_1)

The numpy array r is as follows: [0 1 2 3 4 5 6 7 8 9]
The numpy array r_1 is as follows: [2.  2.4 2.8 3.2 3.6 4. ]


Creating the numpy array with constant interval.

In [24]:
list_array_1 = np.arange(3,10,2)
list_array_2 = np.arange(3,10,0.1)
list_array_3 = np.arange(0.3,10,0.2)

# Number of points using linespace
list_array_4= np.linspace(0, 1, 10)

print(list_array_1)
print(list_array_2)
print(list_array_4)

[3 5 7 9]
[3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7
 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5
 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3
 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


The following lines of the code illustrate the way of performing the arthimatic operations on each element of the list.

In [25]:
marks = [40, 35, 26, 25, 54]  # Write the marks of the class
#new_list1 = 2*marks
#new_list2 = marks+10
new_list1 = []   # Creating the the empty list of marks
for a in marks:
    new_list1.append(a*2)   #new_list1 = marks*2

new_list2 = []
for a in marks:
    new_list2.append(a+10)   #new_list2 = marks+10

print('The marks obtained by squaring the each element of the list (marks)',new_list1)
print('After adding 10 to each element of the list (marks)', new_list2)

The marks obtained by squaring the each element of the list (marks) [80, 70, 52, 50, 108]
After adding 10 to each element of the list (marks) [50, 45, 36, 35, 64]


The numpy library makes it easy to implement the arthimatic operations on every element of the sequence. And this is illustrated by following lines of the code:

In [26]:
marks_np = np.array(marks)  # Converting list(marks) to numpy array (marks_np)
type(marks_np)              # Checking the data type of the array

new_list1 = marks_np*2      # Multiplying each element of the array by 2
new_list2 = marks_np+10     # Adding 10 to every element of the the array
new_list3 = marks_np*2+10   # Multipling by 2 and then adding 10 to the resutant to every element of the array

## Indexing and slicing

Indexing and slicing are also possible using ndarray, and it is quite similar to the list data type.

In [27]:
marks_1= marks_np[1] # Marks of first student 
print(marks_1)

# Marks of the students from 2 to 10
marks_2= marks[2:4]

array_a = np.array([1,2,3,4,5])
array_b = np.array([8,9,10,11,12]) 

array_sum=array_a+array_b            # Adding corresponding elements of array_a and array_b
array_multiply = array_a*array_b     # Multiplying corresponding elements of the array_a and array_b

array_a.dtype # Find the data type of elements
array_b.dtype

print('The summation of two arrays, i.e., array_a and array_b is:',array_sum)
print('The multiplication of two arrays, i.e., array_a and array_b is:',array_multiply)

35
The summation of two arrays, i.e., array_a and array_b is: [ 9 11 13 15 17]
The multiplication of two arrays, i.e., array_a and array_b is: [ 8 18 30 44 60]


In [28]:
numbers = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
numbers[1,2]     # indexing 
q=numbers[0:2,3] # indexing and slicing

In [29]:
print(numbers)
print(numbers.shape)
print(numbers.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [30]:
print(numbers[1,2])     # indexing 
q=numbers[0:2,3] # indexing and slicing

7


In [31]:
print(q)
print(q.shape)
print(q.ndim)

[4 8]
(2,)
1


In [32]:
# Changing the data type from int to float
array_a= array_a.astype('float')
array_b = array_b.astype('float')
array_a.shape

(5,)

## Numpy operations using OOP

In [33]:
numbers = np.array([[6, 10, 14, 18], [10, 7, 14, 11], [15, 12, 6, 14]])

# Methods using OOP
numbers.max()    # method of OOP
numbers.max(0)   # Max. along coloumn

numbers.max(1)   # Max. along row
numbers.mean()   # Calculating the mean 

numbers.std()   # Standard deviation
r=np.histogram(numbers)

numbers.min()
numbers.min(0)  
numbers.min(1)  
numbers.sum(0)

array([31, 29, 34, 43])

## Numpy operations without using OOP

In [34]:
np.max(numbers, axis=0) # Along column
np.max(numbers, axis=1)  # Max. value along row

array([18, 14, 15])

In [36]:
# numpy with boolean 
a= [1,2,3,4,5]
a > 4   

num = [1,4,8,7,9]
num > 3

num1= np.array(num)
num1 > 3


TypeError: ignored

Comparing the every element of the array with 4.

In [37]:
import numpy as np
b= np.array(a)
b > 4

array([False, False, False, False,  True])

In [38]:
num = [1,4,8,7,9]
num > 3

TypeError: ignored

As a list is converted to numpy array, we can compare the obtained array with the constant(3).

In [39]:
num1= np.array(num)
num1 > 3

array([False,  True,  True,  True,  True])

Using math library

In [ ]:
import math
x= [1,2,4,5]
a= 0.1

y= math.sin(x-a)/x

In [ ]:
import numpy as np
a = 5
x = np.linspace(1, 10, 1000)
y = np.sin(x-a)/x
id(y)
x=y
id(x)
# id provides a reference to the memory location where the object is stored

Id provides a reference to the memory location where the object is stored

NumPy views and copies

In [ ]:
# NumPy views and copies
# Copy of the ndarray
numbers = np.array([[6, 10, 14, 18], [10, 7, 14, 11], [15, 12, 6, 14]])
numbers_view = numbers[2:]
numbers_copy= numbers.copy()

Plotting with the numpy array using matplotlib.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
a = 25

x = np.linspace(1, 10, 10000)
y = np.sin(x-a)/x
plt.plot(x, y)
plt.show()

y = np.cos(x-a)/x
plt.plot(x, y)
plt.show()

y = np.exp(x-a)/x
plt.plot(x, y)
plt.show()

##Loading the numpy array from csv file.

Loading the text data from csv file in ndarray.

In [ ]:
import numpy as np
data = np.loadtxt("mean_daily_temperatures_from_1772.csv", delimiter=",", dtype=int)
print(data)
data[0,13]
data[0,:]
data[:,0]
column_2= data[:,1]
print(column_2)